// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using kgs_api.Data;

#nullable disable

namespace kgs_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904030230_AddSavedSearches")]
    partial class AddSavedSearches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Area")
                        .HasColumnType("double precision");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Floors")
                        .HasColumnType("integer");

                    b.Property<double?>("Frontage")
                        .HasColumnType("double precision");

                    b.Property<string>("FurnitureState")
                        .HasColumnType("text");

                    b.Property<string>("HouseDirection")
                        .HasColumnType("text");

                    b.Property<string>("LegalStatus")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TypeProperty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "TypeProperty");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.FileDeletionQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileDeletionQueueItems");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Amenities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BumpedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModerationNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RentPaymentCycle")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', f_unaccent(coalesce(\"Title\", '') || ' ' || coalesce(\"Description\", '')))", true);

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Amenities");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Amenities"), "gin");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetUnitId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("AssetId", "AssetUnitId")
                        .IsUnique()
                        .HasDatabaseName("UX_Listings_OneLivePerSlot")
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.HasIndex("Status", "Type");

                    b.ToTable("Listings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Listing_Price", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.AssetDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseContractId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("LeaseContractId");

                    b.HasIndex("AssetId", "Type");

                    b.ToTable("AssetDocuments");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.AssetMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "TakenAt");

                    b.ToTable("AssetMedia");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.AssetUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Area")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetUnits", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.CashFlowEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetUnitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LeaseContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetUnitId");

                    b.HasIndex("LeaseContractId");

                    b.HasIndex("AssetId", "OccurredAt");

                    b.HasIndex("UserId", "OccurredAt");

                    b.HasIndex("UserId", "Category", "OccurredAt");

                    b.ToTable("CashFlowEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_CashFlow_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.ContactParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Type");

                    b.ToTable("ContactParties");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.LeaseContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextRentIncreaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentContractId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentCycle")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentDueDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TaxResponsibility")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetUnitId");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_LeaseContracts_Active_EndDate")
                        .HasFilter("\"Status\" = 2");

                    b.HasIndex("ParentContractId");

                    b.HasIndex("Status", "EndDate");

                    b.ToTable("LeaseContracts", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaseContract_Dates", "\"EndDate\" > \"StartDate\"");

                            t.HasCheckConstraint("CK_LeaseContract_DueDay", "\"PaymentDueDay\" BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_LeaseContract_Rent", "\"RentAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.ListingInquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConvertedContactPartyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("PreferredViewingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConvertedContactPartyId");

                    b.HasIndex("FromUserId", "CreatedAt");

                    b.HasIndex("ListingId", "FromUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_ListingInquiries_OpenPerUser")
                        .HasFilter("\"Status\" IN (1, 2, 3)");

                    b.HasIndex("ToUserId", "CreatedAt");

                    b.ToTable("ListingInquiries", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Cycle")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseContractId")
                        .HasColumnType("uuid");

                    b.Property<int>("NotifyDaysBefore")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Reminders_Active_DueDate")
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("LeaseContractId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.SavedListing", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ListingId");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId", "SavedAt");

                    b.ToTable("SavedListings", (string)null);
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("NotifyEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastCheckedAt")
                        .HasFilter("\"NotifyEnabled\"");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("SavedSearches", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.Asset", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("kgs_api.Domain.ValueObjects.StoredFile", "Thumbnail", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.OwnsOne("kgs_api.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("AddressDetail");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("District");

                            b1.Property<string>("Ward")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Ward");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Thumbnail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.Listing", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Asset", "Asset")
                        .WithMany("Listings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kgs_api.Domain.Entity.SubEntity.AssetUnit", "AssetUnit")
                        .WithMany()
                        .HasForeignKey("AssetUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("kgs_api.Domain.ValueObjects.ListingTerms", "Terms", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("AvailableFrom")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool?>("CookingAllowed")
                                .HasColumnType("boolean");

                            b1.Property<bool?>("CurfewFree")
                                .HasColumnType("boolean");

                            b1.Property<int?>("DepositMonths")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("ElectricityPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("InternetFee")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int?>("MaxOccupants")
                                .HasColumnType("integer");

                            b1.Property<int?>("MinLeaseMonths")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("ParkingFee")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<bool?>("PetsAllowed")
                                .HasColumnType("boolean");

                            b1.Property<decimal?>("ServiceFee")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<bool?>("SharedWithOwner")
                                .HasColumnType("boolean");

                            b1.Property<decimal?>("WaterPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int?>("WaterPricing")
                                .HasColumnType("integer");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("Asset");

                    b.Navigation("AssetUnit");

                    b.Navigation("Terms")
                        .IsRequired();
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.RefreshToken", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.AssetDocument", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Asset", "Asset")
                        .WithMany("Documents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kgs_api.Domain.Entity.SubEntity.LeaseContract", "LeaseContract")
                        .WithMany("Documents")
                        .HasForeignKey("LeaseContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("kgs_api.Domain.ValueObjects.StoredFile", "File", b1 =>
                        {
                            b1.Property<Guid>("AssetDocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("AssetDocumentId");

                            b1.ToTable("AssetDocuments");

                            b1.WithOwner()
                                .HasForeignKey("AssetDocumentId");
                        });

                    b.Navigation("Asset");

                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("LeaseContract");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.AssetMedia", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Asset", "Asset")
                        .WithMany("Media")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("kgs_api.Domain.ValueObjects.StoredFile", "File", b1 =>
                        {
                            b1.Property<Guid>("AssetMediaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("AssetMediaId");

                            b1.HasIndex("PublicId");

                            b1.ToTable("AssetMedia");

                            b1.WithOwner()
                                .HasForeignKey("AssetMediaId");
                        });

                    b.Navigation("Asset");

                    b.Navigation("File")
                        .IsRequired();
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.AssetUnit", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Asset", "Asset")
                        .WithMany("Units")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.CashFlowEntry", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Asset", "Asset")
                        .WithMany("CashFlows")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kgs_api.Domain.Entity.SubEntity.AssetUnit", "AssetUnit")
                        .WithMany()
                        .HasForeignKey("AssetUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("kgs_api.Domain.Entity.SubEntity.LeaseContract", "LeaseContract")
                        .WithMany()
                        .HasForeignKey("LeaseContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("kgs_api.Domain.ValueObjects.StoredFile", "Receipt", b1 =>
                        {
                            b1.Property<Guid>("CashFlowEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("CashFlowEntryId");

                            b1.ToTable("CashFlowEntries");

                            b1.WithOwner()
                                .HasForeignKey("CashFlowEntryId");
                        });

                    b.Navigation("Asset");

                    b.Navigation("AssetUnit");

                    b.Navigation("LeaseContract");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.ContactParty", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.LeaseContract", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Asset", "Asset")
                        .WithMany("Contracts")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kgs_api.Domain.Entity.SubEntity.AssetUnit", "AssetUnit")
                        .WithMany()
                        .HasForeignKey("AssetUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("kgs_api.Domain.Entity.SubEntity.ContactParty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kgs_api.Domain.Entity.SubEntity.LeaseContract", "ParentContract")
                        .WithMany()
                        .HasForeignKey("ParentContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("AssetUnit");

                    b.Navigation("Counterparty");

                    b.Navigation("ParentContract");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.ListingImage", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("kgs_api.Domain.ValueObjects.StoredFile", "File", b1 =>
                        {
                            b1.Property<Guid>("ListingImageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("ListingImageId");

                            b1.ToTable("ListingImages");

                            b1.WithOwner()
                                .HasForeignKey("ListingImageId");
                        });

                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.ListingInquiry", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.SubEntity.ContactParty", "ConvertedContactParty")
                        .WithMany()
                        .HasForeignKey("ConvertedContactPartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kgs_api.Domain.Entity.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConvertedContactParty");

                    b.Navigation("FromUser");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.Reminder", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("kgs_api.Domain.Entity.SubEntity.LeaseContract", "LeaseContract")
                        .WithMany()
                        .HasForeignKey("LeaseContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Asset");

                    b.Navigation("LeaseContract");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.SavedListing", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.SavedSearch", b =>
                {
                    b.HasOne("kgs_api.Domain.Entity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.Asset", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("Contracts");

                    b.Navigation("Documents");

                    b.Navigation("Listings");

                    b.Navigation("Media");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.Listing", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("kgs_api.Domain.Entity.SubEntity.LeaseContract", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
