/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as DangTinRouteImport } from './routes/dang-tin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TinCuaToiRouteImport } from './routes/tin-cua-toi'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as DaLuuIndexRouteImport } from './routes/da-luu.index'
import { Route as QuanLyIndexRouteImport } from './routes/quan-ly.index'
import { Route as TinDangIndexRouteImport } from './routes/tin-dang.index'
import { Route as TinDangSlugRouteImport } from './routes/tin-dang.$slug'
import { Route as YeuCauIndexRouteImport } from './routes/yeu-cau.index'
import { Route as QuanLyBanDoIndexRouteImport } from './routes/quan-ly.ban-do.index'
import { Route as QuanLyDoiTacIndexRouteImport } from './routes/quan-ly.doi-tac.index'
import { Route as QuanLyHopDongIndexRouteImport } from './routes/quan-ly.hop-dong.index'
import { Route as QuanLyHopDongIdRouteImport } from './routes/quan-ly.hop-dong.$id'
import { Route as QuanLyHopDongMoiRouteImport } from './routes/quan-ly.hop-dong.moi'
import { Route as QuanLyNhacLichIndexRouteImport } from './routes/quan-ly.nhac-lich.index'
import { Route as QuanLyTaiSanIndexRouteImport } from './routes/quan-ly.tai-san.index'
import { Route as QuanLyTaiSanIdRouteImport } from './routes/quan-ly.tai-san.$id'
import { Route as QuanLyTaiSanMoiRouteImport } from './routes/quan-ly.tai-san.moi'
import { Route as QuanLyThuChiIndexRouteImport } from './routes/quan-ly.thu-chi.index'
import { Route as QuanLyTaiSanIdSuaRouteImport } from './routes/quan-ly.tai-san.$id_.sua'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DangTinRoute = DangTinRouteImport.update({
  id: '/dang-tin',
  path: '/dang-tin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TinCuaToiRoute = TinCuaToiRouteImport.update({
  id: '/tin-cua-toi',
  path: '/tin-cua-toi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DaLuuIndexRoute = DaLuuIndexRouteImport.update({
  id: '/da-luu/',
  path: '/da-luu/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyIndexRoute = QuanLyIndexRouteImport.update({
  id: '/quan-ly/',
  path: '/quan-ly/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinDangIndexRoute = TinDangIndexRouteImport.update({
  id: '/tin-dang/',
  path: '/tin-dang/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinDangSlugRoute = TinDangSlugRouteImport.update({
  id: '/tin-dang/$slug',
  path: '/tin-dang/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const YeuCauIndexRoute = YeuCauIndexRouteImport.update({
  id: '/yeu-cau/',
  path: '/yeu-cau/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyBanDoIndexRoute = QuanLyBanDoIndexRouteImport.update({
  id: '/quan-ly/ban-do/',
  path: '/quan-ly/ban-do/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyDoiTacIndexRoute = QuanLyDoiTacIndexRouteImport.update({
  id: '/quan-ly/doi-tac/',
  path: '/quan-ly/doi-tac/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyHopDongIndexRoute = QuanLyHopDongIndexRouteImport.update({
  id: '/quan-ly/hop-dong/',
  path: '/quan-ly/hop-dong/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyHopDongIdRoute = QuanLyHopDongIdRouteImport.update({
  id: '/quan-ly/hop-dong/$id',
  path: '/quan-ly/hop-dong/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyHopDongMoiRoute = QuanLyHopDongMoiRouteImport.update({
  id: '/quan-ly/hop-dong/moi',
  path: '/quan-ly/hop-dong/moi',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyNhacLichIndexRoute = QuanLyNhacLichIndexRouteImport.update({
  id: '/quan-ly/nhac-lich/',
  path: '/quan-ly/nhac-lich/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyTaiSanIndexRoute = QuanLyTaiSanIndexRouteImport.update({
  id: '/quan-ly/tai-san/',
  path: '/quan-ly/tai-san/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyTaiSanIdRoute = QuanLyTaiSanIdRouteImport.update({
  id: '/quan-ly/tai-san/$id',
  path: '/quan-ly/tai-san/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyTaiSanMoiRoute = QuanLyTaiSanMoiRouteImport.update({
  id: '/quan-ly/tai-san/moi',
  path: '/quan-ly/tai-san/moi',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyThuChiIndexRoute = QuanLyThuChiIndexRouteImport.update({
  id: '/quan-ly/thu-chi/',
  path: '/quan-ly/thu-chi/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyTaiSanIdSuaRoute = QuanLyTaiSanIdSuaRouteImport.update({
  id: '/quan-ly/tai-san/$id_/sua',
  path: '/quan-ly/tai-san/$id/sua',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/confirm-email': typeof ConfirmEmailRoute
  '/dang-tin': typeof DangTinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tin-cua-toi': typeof TinCuaToiRoute
  '/admin/listings': typeof AdminListingsRoute
  '/tin-dang/$slug': typeof TinDangSlugRoute
  '/da-luu/': typeof DaLuuIndexRoute
  '/quan-ly/': typeof QuanLyIndexRoute
  '/tin-dang/': typeof TinDangIndexRoute
  '/yeu-cau/': typeof YeuCauIndexRoute
  '/quan-ly/hop-dong/$id': typeof QuanLyHopDongIdRoute
  '/quan-ly/hop-dong/moi': typeof QuanLyHopDongMoiRoute
  '/quan-ly/tai-san/$id': typeof QuanLyTaiSanIdRoute
  '/quan-ly/tai-san/moi': typeof QuanLyTaiSanMoiRoute
  '/quan-ly/ban-do/': typeof QuanLyBanDoIndexRoute
  '/quan-ly/doi-tac/': typeof QuanLyDoiTacIndexRoute
  '/quan-ly/hop-dong/': typeof QuanLyHopDongIndexRoute
  '/quan-ly/nhac-lich/': typeof QuanLyNhacLichIndexRoute
  '/quan-ly/tai-san/': typeof QuanLyTaiSanIndexRoute
  '/quan-ly/thu-chi/': typeof QuanLyThuChiIndexRoute
  '/quan-ly/tai-san/$id/sua': typeof QuanLyTaiSanIdSuaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/confirm-email': typeof ConfirmEmailRoute
  '/dang-tin': typeof DangTinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tin-cua-toi': typeof TinCuaToiRoute
  '/admin/listings': typeof AdminListingsRoute
  '/tin-dang/$slug': typeof TinDangSlugRoute
  '/da-luu': typeof DaLuuIndexRoute
  '/quan-ly': typeof QuanLyIndexRoute
  '/tin-dang': typeof TinDangIndexRoute
  '/yeu-cau': typeof YeuCauIndexRoute
  '/quan-ly/hop-dong/$id': typeof QuanLyHopDongIdRoute
  '/quan-ly/hop-dong/moi': typeof QuanLyHopDongMoiRoute
  '/quan-ly/tai-san/$id': typeof QuanLyTaiSanIdRoute
  '/quan-ly/tai-san/moi': typeof QuanLyTaiSanMoiRoute
  '/quan-ly/ban-do': typeof QuanLyBanDoIndexRoute
  '/quan-ly/doi-tac': typeof QuanLyDoiTacIndexRoute
  '/quan-ly/hop-dong': typeof QuanLyHopDongIndexRoute
  '/quan-ly/nhac-lich': typeof QuanLyNhacLichIndexRoute
  '/quan-ly/tai-san': typeof QuanLyTaiSanIndexRoute
  '/quan-ly/thu-chi': typeof QuanLyThuChiIndexRoute
  '/quan-ly/tai-san/$id/sua': typeof QuanLyTaiSanIdSuaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/confirm-email': typeof ConfirmEmailRoute
  '/dang-tin': typeof DangTinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tin-cua-toi': typeof TinCuaToiRoute
  '/admin/listings': typeof AdminListingsRoute
  '/tin-dang/$slug': typeof TinDangSlugRoute
  '/da-luu/': typeof DaLuuIndexRoute
  '/quan-ly/': typeof QuanLyIndexRoute
  '/tin-dang/': typeof TinDangIndexRoute
  '/yeu-cau/': typeof YeuCauIndexRoute
  '/quan-ly/hop-dong/$id': typeof QuanLyHopDongIdRoute
  '/quan-ly/hop-dong/moi': typeof QuanLyHopDongMoiRoute
  '/quan-ly/tai-san/$id': typeof QuanLyTaiSanIdRoute
  '/quan-ly/tai-san/moi': typeof QuanLyTaiSanMoiRoute
  '/quan-ly/ban-do/': typeof QuanLyBanDoIndexRoute
  '/quan-ly/doi-tac/': typeof QuanLyDoiTacIndexRoute
  '/quan-ly/hop-dong/': typeof QuanLyHopDongIndexRoute
  '/quan-ly/nhac-lich/': typeof QuanLyNhacLichIndexRoute
  '/quan-ly/tai-san/': typeof QuanLyTaiSanIndexRoute
  '/quan-ly/thu-chi/': typeof QuanLyThuChiIndexRoute
  '/quan-ly/tai-san/$id_/sua': typeof QuanLyTaiSanIdSuaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/confirm-email'
    | '/dang-tin'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/tin-cua-toi'
    | '/admin/listings'
    | '/tin-dang/$slug'
    | '/da-luu/'
    | '/quan-ly/'
    | '/tin-dang/'
    | '/yeu-cau/'
    | '/quan-ly/hop-dong/$id'
    | '/quan-ly/hop-dong/moi'
    | '/quan-ly/tai-san/$id'
    | '/quan-ly/tai-san/moi'
    | '/quan-ly/ban-do/'
    | '/quan-ly/doi-tac/'
    | '/quan-ly/hop-dong/'
    | '/quan-ly/nhac-lich/'
    | '/quan-ly/tai-san/'
    | '/quan-ly/thu-chi/'
    | '/quan-ly/tai-san/$id/sua'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/confirm-email'
    | '/dang-tin'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/tin-cua-toi'
    | '/admin/listings'
    | '/tin-dang/$slug'
    | '/da-luu'
    | '/quan-ly'
    | '/tin-dang'
    | '/yeu-cau'
    | '/quan-ly/hop-dong/$id'
    | '/quan-ly/hop-dong/moi'
    | '/quan-ly/tai-san/$id'
    | '/quan-ly/tai-san/moi'
    | '/quan-ly/ban-do'
    | '/quan-ly/doi-tac'
    | '/quan-ly/hop-dong'
    | '/quan-ly/nhac-lich'
    | '/quan-ly/tai-san'
    | '/quan-ly/thu-chi'
    | '/quan-ly/tai-san/$id/sua'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/confirm-email'
    | '/dang-tin'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/tin-cua-toi'
    | '/admin/listings'
    | '/tin-dang/$slug'
    | '/da-luu/'
    | '/quan-ly/'
    | '/tin-dang/'
    | '/yeu-cau/'
    | '/quan-ly/hop-dong/$id'
    | '/quan-ly/hop-dong/moi'
    | '/quan-ly/tai-san/$id'
    | '/quan-ly/tai-san/moi'
    | '/quan-ly/ban-do/'
    | '/quan-ly/doi-tac/'
    | '/quan-ly/hop-dong/'
    | '/quan-ly/nhac-lich/'
    | '/quan-ly/tai-san/'
    | '/quan-ly/thu-chi/'
    | '/quan-ly/tai-san/$id_/sua'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  DangTinRoute: typeof DangTinRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TinCuaToiRoute: typeof TinCuaToiRoute
  AdminListingsRoute: typeof AdminListingsRoute
  TinDangSlugRoute: typeof TinDangSlugRoute
  DaLuuIndexRoute: typeof DaLuuIndexRoute
  QuanLyIndexRoute: typeof QuanLyIndexRoute
  TinDangIndexRoute: typeof TinDangIndexRoute
  YeuCauIndexRoute: typeof YeuCauIndexRoute
  QuanLyHopDongIdRoute: typeof QuanLyHopDongIdRoute
  QuanLyHopDongMoiRoute: typeof QuanLyHopDongMoiRoute
  QuanLyTaiSanIdRoute: typeof QuanLyTaiSanIdRoute
  QuanLyTaiSanMoiRoute: typeof QuanLyTaiSanMoiRoute
  QuanLyBanDoIndexRoute: typeof QuanLyBanDoIndexRoute
  QuanLyDoiTacIndexRoute: typeof QuanLyDoiTacIndexRoute
  QuanLyHopDongIndexRoute: typeof QuanLyHopDongIndexRoute
  QuanLyNhacLichIndexRoute: typeof QuanLyNhacLichIndexRoute
  QuanLyTaiSanIndexRoute: typeof QuanLyTaiSanIndexRoute
  QuanLyThuChiIndexRoute: typeof QuanLyThuChiIndexRoute
  QuanLyTaiSanIdSuaRoute: typeof QuanLyTaiSanIdSuaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-tin': {
      id: '/dang-tin'
      path: '/dang-tin'
      fullPath: '/dang-tin'
      preLoaderRoute: typeof DangTinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-cua-toi': {
      id: '/tin-cua-toi'
      path: '/tin-cua-toi'
      fullPath: '/tin-cua-toi'
      preLoaderRoute: typeof TinCuaToiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/da-luu/': {
      id: '/da-luu/'
      path: '/da-luu'
      fullPath: '/da-luu/'
      preLoaderRoute: typeof DaLuuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/': {
      id: '/quan-ly/'
      path: '/quan-ly'
      fullPath: '/quan-ly/'
      preLoaderRoute: typeof QuanLyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-dang/': {
      id: '/tin-dang/'
      path: '/tin-dang'
      fullPath: '/tin-dang/'
      preLoaderRoute: typeof TinDangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-dang/$slug': {
      id: '/tin-dang/$slug'
      path: '/tin-dang/$slug'
      fullPath: '/tin-dang/$slug'
      preLoaderRoute: typeof TinDangSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yeu-cau/': {
      id: '/yeu-cau/'
      path: '/yeu-cau'
      fullPath: '/yeu-cau/'
      preLoaderRoute: typeof YeuCauIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/ban-do/': {
      id: '/quan-ly/ban-do/'
      path: '/quan-ly/ban-do'
      fullPath: '/quan-ly/ban-do/'
      preLoaderRoute: typeof QuanLyBanDoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/doi-tac/': {
      id: '/quan-ly/doi-tac/'
      path: '/quan-ly/doi-tac'
      fullPath: '/quan-ly/doi-tac/'
      preLoaderRoute: typeof QuanLyDoiTacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/hop-dong/': {
      id: '/quan-ly/hop-dong/'
      path: '/quan-ly/hop-dong'
      fullPath: '/quan-ly/hop-dong/'
      preLoaderRoute: typeof QuanLyHopDongIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/hop-dong/$id': {
      id: '/quan-ly/hop-dong/$id'
      path: '/quan-ly/hop-dong/$id'
      fullPath: '/quan-ly/hop-dong/$id'
      preLoaderRoute: typeof QuanLyHopDongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/hop-dong/moi': {
      id: '/quan-ly/hop-dong/moi'
      path: '/quan-ly/hop-dong/moi'
      fullPath: '/quan-ly/hop-dong/moi'
      preLoaderRoute: typeof QuanLyHopDongMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/nhac-lich/': {
      id: '/quan-ly/nhac-lich/'
      path: '/quan-ly/nhac-lich'
      fullPath: '/quan-ly/nhac-lich/'
      preLoaderRoute: typeof QuanLyNhacLichIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/tai-san/': {
      id: '/quan-ly/tai-san/'
      path: '/quan-ly/tai-san'
      fullPath: '/quan-ly/tai-san/'
      preLoaderRoute: typeof QuanLyTaiSanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/tai-san/$id': {
      id: '/quan-ly/tai-san/$id'
      path: '/quan-ly/tai-san/$id'
      fullPath: '/quan-ly/tai-san/$id'
      preLoaderRoute: typeof QuanLyTaiSanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/tai-san/moi': {
      id: '/quan-ly/tai-san/moi'
      path: '/quan-ly/tai-san/moi'
      fullPath: '/quan-ly/tai-san/moi'
      preLoaderRoute: typeof QuanLyTaiSanMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/thu-chi/': {
      id: '/quan-ly/thu-chi/'
      path: '/quan-ly/thu-chi'
      fullPath: '/quan-ly/thu-chi/'
      preLoaderRoute: typeof QuanLyThuChiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly/tai-san/$id_/sua': {
      id: '/quan-ly/tai-san/$id_/sua'
      path: '/quan-ly/tai-san/$id/sua'
      fullPath: '/quan-ly/tai-san/$id/sua'
      preLoaderRoute: typeof QuanLyTaiSanIdSuaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  ConfirmEmailRoute: ConfirmEmailRoute,
  DangTinRoute: DangTinRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TinCuaToiRoute: TinCuaToiRoute,
  AdminListingsRoute: AdminListingsRoute,
  TinDangSlugRoute: TinDangSlugRoute,
  DaLuuIndexRoute: DaLuuIndexRoute,
  QuanLyIndexRoute: QuanLyIndexRoute,
  TinDangIndexRoute: TinDangIndexRoute,
  YeuCauIndexRoute: YeuCauIndexRoute,
  QuanLyHopDongIdRoute: QuanLyHopDongIdRoute,
  QuanLyHopDongMoiRoute: QuanLyHopDongMoiRoute,
  QuanLyTaiSanIdRoute: QuanLyTaiSanIdRoute,
  QuanLyTaiSanMoiRoute: QuanLyTaiSanMoiRoute,
  QuanLyBanDoIndexRoute: QuanLyBanDoIndexRoute,
  QuanLyDoiTacIndexRoute: QuanLyDoiTacIndexRoute,
  QuanLyHopDongIndexRoute: QuanLyHopDongIndexRoute,
  QuanLyNhacLichIndexRoute: QuanLyNhacLichIndexRoute,
  QuanLyTaiSanIndexRoute: QuanLyTaiSanIndexRoute,
  QuanLyThuChiIndexRoute: QuanLyThuChiIndexRoute,
  QuanLyTaiSanIdSuaRoute: QuanLyTaiSanIdSuaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
